wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.40.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714010985.862007
    t:
      1:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 23
      4: 3.11.5
      5: 0.16.3
      6: 4.40.0
      8:
      - 5
      13: linux-x86_64
